### ISSUE TITLE
unable to install on python 3.6 ubuntu 16.04

### ISSUE THREAD

**Issue by lepmik** [wxWidgets/wxPython#15]
Hi, when using pip install I get the following error

```
FileNotFoundError: [Errno 2] No such file or directory: 'sip/cpp/_core.sbf'
Command '"/home/mikkel/apps/anaconda3/envs/psychopy/bin/python" /home/mikkel/apps/Phoenix/bin/waf-1.7.15-p1 --wx_config=/home/mikkel/apps/Phoenix/build/wx-config --python="/home/mikkel/apps/anaconda3/envs/psychopy/bin/python" --out=build/waf/3.6 configure build ' failed with exit code 2.
Finished command: build_py (0m1.638s)
Finished command: build (1m56.259s)
```

I am using a anaconda environment 

```
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```

**Comment by RobinD42** [comment]
A few things:

1. I've verified that that file is present in the source tarball. Perhaps something happened when pip was downloading it? Or something stomped on the build folder before it got to that point? 

2. There is a conda recipe for wxPython-phoenix at https://anaconda.org/newville/wxpython-phoenix, you may have more success using that.

3. I just tried building from scratch with pip on a LinuxMint system that uses Ubuntu 16.04 as the base system, and it succeeded.  You could try using the `-v` flag so all the build steps and their output are printed and see if there are any more clues revealed about the problem.

4. This github project is for Classic wxPython (versions < 4). If you are still having troubles please file a new report at https://github.com/wxWidgets/Phoenix, referencing this one for continuity.
