### ISSUE TITLE
How to set  wx.DataViewListCtrl  item data in row?

### ISSUE THREAD

**Issue by noval102200** [wxWidgets/wxPython#24]
I see the document say AppendItem has a data parament,but the type is wx.UIntPtr，how to contert python object to this type?

**Comment by RobinD42** [comment]
The `wxUIntPtr` type in C++ is basically just an unsigned integer that is guaranteed to be large enough to also hold a pointer. For wxPython that means that all you can store is an integer as your data value associated with the item, but you can use that integer as an index or key into some other data structure if needed.
