### ISSUE TITLE
Choosing Multiple Files and Their Order

### ISSUE THREAD

**Issue by spot92** [wxWidgets/wxPython#35]
I would like when I choose multiple files for them to be listed in the order I chose them, not alphabetically. What do I need to change to do this? I have asked here and on the Gooey repo as I am uncertain about where to ask this.

Edit: it appears to do so only when the number of files is greater than 2.

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
