### ISSUE TITLE
Image resizing algorithm in wxPython Canvas

### ISSUE THREAD

**Issue by josephernest** [wxWidgets/wxPython#8]
I'm using a Canvas with

    img = wx.Image('test.png')
    self.Canvas.AddScaledBitmap(img, (0,0), Height=img.GetHeight(), Position = 'tl')

and I noticed that when resizing the canvas, the image is resized. That's ok, that's what I want.

But the resizing algorithm doesn't give sharp result when the input input is resized, especially when image contains text.

**Is it possible to change the image resizing algorithm used in canvas ScaledBitmap?**

**Comment by josephernest** [comment]
Any idea @RobinD42? 

In which line / file is the resizing algorithm chosen (among nearest, bilinear, etc.) ?

**Comment by RobinD42** [comment]
You should be able to find it in the `ScaledBitmap` class in `wx/lib/floatcanvas/FloatCanvas.py`. A quick look there shows that you can set a `Quality` property which is then used when scaling the image.

**Comment by josephernest** [comment]
Thanks. Even with `Quality` set to `high`, the quality is not as good as other standard scaling general purpose algorithms. Where could I modify https://wxpython.org/docs/api/wx.Image-class.html#Scale algorithm in wx.Image itself?

**Comment by josephernest** [comment]
In _core.py, I find this:

    IMAGE_QUALITY_NEAREST = _core_.IMAGE_QUALITY_NEAREST
    IMAGE_QUALITY_BILINEAR = _core_.IMAGE_QUALITY_BILINEAR
    IMAGE_QUALITY_BICUBIC = _core_.IMAGE_QUALITY_BICUBIC
    IMAGE_QUALITY_BOX_AVERAGE = _core_.IMAGE_QUALITY_BOX_AVERAGE
    IMAGE_QUALITY_NORMAL = _core_.IMAGE_QUALITY_NORMAL
    IMAGE_QUALITY_HIGH = _core_.IMAGE_QUALITY_HIGH

How is it possible to test all these algorithms in a `ScaledBitmap` ?

**Comment by RobinD42** [comment]
Just like anything else, either modify the code to behave the way you want, or derive a new class from `ScaledBitmap`, override the things you want to change and use that class instead.

**Comment by josephernest** [comment]
Thanks @RobinD42 a lot. Problem solved by displaying all algorithms:

```
import wx

class MainPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent, -1, style=wx.FULL_REPAINT_ON_RESIZE)
        self.Bind(wx.EVT_PAINT, self.OnPaint)

    def OnPaint(self, event):
        dc = wx.PaintDC(self)
        img = wx.Image('a.png', wx.BITMAP_TYPE_PNG)
        for i, quality in enumerate([wx.IMAGE_QUALITY_NEAREST, wx.IMAGE_QUALITY_BILINEAR, wx.IMAGE_QUALITY_BICUBIC, wx.IMAGE_QUALITY_BOX_AVERAGE, wx.IMAGE_QUALITY_NORMAL, wx.IMAGE_QUALITY_HIGH]):
            dc.DrawBitmap(wx.BitmapFromImage(img.Scale(67, 68.5, quality=quality)),i*70,0)

class MainFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, -1, title='Test', size=(600,400))
        self.panel = MainPanel(self)
        self.Show()
        
app = wx.App(0)
frame = MainFrame(None)
app.MainLoop()        
```

Then I noticed `wx.IMAGE_QUALITY_BILINEAR` was the best for my purpose!
